name: WhatsApp Bot Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t whatsapp-bot .

      # Step 4: Run the Docker container in detached mode
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 whatsapp-bot

      # Step 5: Install ngrok
      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && \
          sudo apt-get update && sudo apt-get install ngrok

      # Step 6: Start ngrok with the authtoken
      - name: Start ngrok
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN }}
          nohup ngrok http 3000 &

      # Step 7: Get the ngrok URL
      - name: Get ngrok URL
        run: |
          sleep 5
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
